### ISSUE TITLE
Use image instead of link

### ISSUE THREAD

**Issue by gaocegege** [dyweb/acg-detector#1]
```[]() -> ![]()```

**Comment by clouduan** [comment]
是的我试了，但是截取图像的尺寸问题会导致排版之后看起来奇丑无比 😭

**Comment by gaocegege** [comment]
Then you could have a look at:

```
<div align="center">
	<img src="./raw-docs/img/editor.png" alt="Editor" width="500">
</div>
```

**Comment by gaocegege** [comment]
@clouduan 我来试试吧

**Comment by clouduan** [comment]
OK

**Comment by gaocegege** [comment]
@clouduan 你那个问题是因为 GitHub 的 preview 不支持 HTML 居中，不是不能居中，在渲染 README 的时候就可以了

**Comment by clouduan** [comment]
原来 **GitHub 的 preview 不支持 HTML 居中** 啊，明白了，谢谢！

**Comment by xplorld** [comment]
居中。。。

**Comment by clouduan** [comment]
做了一件 ruiyang 大佬极力不推荐的操作 :sweat_smile:

**Comment by gaocegege** [comment]
对不起 ruiyang 大佬，让你失望了

鞠躬

**Comment by xplorld** [comment]
![nicky](https://img.moegirl.org/common/thumb/4/41/Nicky.jpg/250px-Nicky.jpg)
