### ISSUE TITLE
Upload the extension into web store

### ISSUE THREAD

**Issue by clouduan** [dyweb/acg-detector#3]
/cc @at15 

v0.1.1 has been released. Would you please upload it to Chrome Web Store?

https://github.com/dyweb/acg-detector/releases/tag/v0.1.0

Thanks in advance!

**Comment by at15** [comment]
released https://chrome.google.com/webstore/detail/acg-detector/kabdhpcjocieboohkggemdilfjgonhci

**Comment by clouduan** [comment]
Thanks a lot! A cup of tea for you, big boss! :tea:

**Comment by at15** [comment]
need to add chrome web store linke to readme @clouduan

**Comment by clouduan** [comment]
Completed.

**Comment by at15** [comment]
you can refer to the issue in your commit message
