### ISSUE TITLE
[bug] Can't switch tab on certain websites

### ISSUE THREAD

**Issue by at15** [dyweb/acg-detector#5]
It seems the plugin is doing something it should not do .... i.e. https://tiledb.io/#rec45683519 disable the plugin and switching tab worked ....

Also

- [ ] logging in console is not disabled

**Comment by clouduan** [comment]
嗯是的，目前对于网页中 Video ID 的识别效果很糟糕。我只做了简单的字符匹配，所以错误很多。我已经将其加入 [todo list](https://github.com/dyweb/acg-detector#-todo) 里面了，希望之后能优化一下。

BTW，
> logging in console is not disabled

指的是什么？我没懂，能详细说下吗？

**Comment by at15** [comment]
@clouduan 你代码里有 `console.log` 这个在正式发布的版本里是不应该有的。

![image](https://user-images.githubusercontent.com/5621298/38292123-6682bf26-3797-11e8-8158-45e5fc264a64.png)


匹配不是优化的问题啊，你不改的话别人正常网页有很大概率看不了的 ....  这个网页你的正则把 `<div id="nav32711946marker"></div>` 匹配出来了 `av32711946` ...

**Comment by xplorld** [comment]
可以 console.log 一下东岳招新 /w\

**Comment by clouduan** [comment]
@at15
1. `console.log` 我回去马上拿掉。
2. 这个可以在选项里面设置“加载网页时不替换”，我可能需要把默认值改为否…
